// <auto-generated />
using CWPT.Interviews.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CWPT.Interviews.Test.Migrations
{
    [DbContext(typeof(PracticeContext))]
    partial class PracticeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24");

            modelBuilder.Entity("CWPT.Interviews.Test.Practice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("AddressLine3")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT")
                        .HasMaxLength(12);

                    b.HasKey("Id");

                    b.ToTable("Practices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "The Barley Lea",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.5020543",
                            Longitude = "52.3959894",
                            Name = "Stoke Aldermoor Medical Centre",
                            Postcode = "CV3 1EG"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "School St",
                            AddressLine2 = "Wolston",
                            AddressLine3 = "Coventry",
                            Latitude = "-1.5419026",
                            Longitude = "52.3740129",
                            Name = "Wolston Surgery",
                            Postcode = "CV8 3HG"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "42 St Paul's Road",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.5510533",
                            Longitude = "52.4042861",
                            Name = "Central Medical Centre",
                            Postcode = "CV6 5DF"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine1 = "41 Westminster Road",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.5437157",
                            Longitude = "52.3932425",
                            Name = "Jubilee Health Care",
                            Postcode = "CV1 3GB"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine1 = "201 Wigston Rd",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.4769648",
                            Longitude = "52.4126748",
                            Name = "Woodway Medical Centre",
                            Postcode = "CV2 2RH"
                        },
                        new
                        {
                            Id = 6,
                            AddressLine1 = "2 St George's Road",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.544966",
                            Longitude = "52.3915094",
                            Name = "Park House Surgery",
                            Postcode = "CV1 2DL"
                        },
                        new
                        {
                            Id = 7,
                            AddressLine1 = "95 Momus Blvd",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.5753546",
                            Longitude = "52.3836432",
                            Name = "Copsewood Medical Centre",
                            Postcode = "CV2 5NB"
                        },
                        new
                        {
                            Id = 8,
                            AddressLine1 = "15 Chace Avenue",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.5431221",
                            Longitude = "52.3760257",
                            Name = "Kenyon Medical Centre",
                            Postcode = "CV3 3AD"
                        },
                        new
                        {
                            Id = 9,
                            AddressLine1 = "298 Tile Hill Lane",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.5670089",
                            Longitude = "52.3966523",
                            Name = "Westwood Medical Centre",
                            Postcode = "CV4 9DR"
                        },
                        new
                        {
                            Id = 10,
                            AddressLine1 = "103 Leamington Road",
                            AddressLine2 = "Coventry",
                            AddressLine3 = "",
                            Latitude = "-1.515459",
                            Longitude = "52.390024",
                            Name = "Phoenix Family Care",
                            Postcode = "CV3 6GQ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
